# Generated by Django 5.1.15 on 2026-06-12 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, help_text='Ex : Censeur, Comptable, Surveillant', max_length=100, verbose_name='titre du poste'),
        ),
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_payments', models.BooleanField(default=False, verbose_name='voir les paiements')),
                ('can_create_payments', models.BooleanField(default=False, verbose_name='enregistrer des paiements')),
                ('can_cancel_payments', models.BooleanField(default=False, verbose_name='annuler des paiements')),
                ('can_view_students', models.BooleanField(default=True, verbose_name='voir les élèves')),
                ('can_create_students', models.BooleanField(default=False, verbose_name='inscrire des élèves')),
                ('can_edit_students', models.BooleanField(default=False, verbose_name='modifier les fiches')),
                ('can_view_notes', models.BooleanField(default=False, verbose_name='voir les notes')),
                ('can_edit_notes', models.BooleanField(default=False, verbose_name='saisir / modifier les notes')),
                ('can_generate_bulletins', models.BooleanField(default=False, verbose_name='générer les bulletins')),
                ('can_download_bulletins', models.BooleanField(default=False, verbose_name='télécharger les bulletins')),
                ('can_record_absences', models.BooleanField(default=False, verbose_name='enregistrer les absences')),
                ('can_view_classes', models.BooleanField(default=True, verbose_name='voir les classes')),
                ('can_edit_classes', models.BooleanField(default=False, verbose_name='modifier les classes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staff_permission', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'permission staff',
                'verbose_name_plural': 'permissions staff',
            },
        ),
    ]
