# Generated by Django 5.1.15 on 2026-06-13 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_job_title_staff_permissions'),
        ('schools', '0012_add_school_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'Directeur'), ('staff', 'Staff / Secrétaire'), ('teacher', 'Professeur'), ('student', 'Élève'), ('parent', 'Parent'), ('promoter', 'Promoteur')], default='staff', max_length=20, verbose_name='rôle'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', 'Directeur'), ('staff', 'Staff / Secrétaire'), ('teacher', 'Professeur'), ('student', 'Élève'), ('parent', 'Parent'), ('promoter', 'Promoteur')], max_length=20, verbose_name='rôle')),
                ('job_title', models.CharField(blank=True, help_text='Ex : Censeur, Comptable, Surveillant', max_length=100, verbose_name='titre du poste')),
                ('is_default', models.BooleanField(default=False, help_text='École ouverte automatiquement à la connexion', verbose_name='école par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='schools.school', verbose_name='école')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'appartenance',
                'verbose_name_plural': 'appartenances',
            },
        ),
        migrations.AddField(
            model_name='staffpermission',
            name='membership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_permission', to='accounts.membership', verbose_name='appartenance'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'is_active'], name='membership_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['school', 'role'], name='membership_school_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'school'), name='unique_user_school_membership'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='uniq_default_membership_user'),
        ),
    ]
