# Generated by Django 5.1.15 on 2026-06-13 17:16
#
# Phase B — Migration de données multi-école.
# Backfill additif et idempotent (get_or_create) : peut être rejouée sans
# créer de doublons. Réversible (reverse = noop : on ne détruit aucune donnée
# existante au rollback ; les tables sont supprimées par les migrations schéma).

from django.db import migrations


def backfill_memberships(apps, schema_editor):
    """Crée un Membership par défaut pour chaque User rattaché à une école."""
    User = apps.get_model('accounts', 'User')
    Membership = apps.get_model('accounts', 'Membership')

    users_with_school = User.objects.filter(
        school__isnull=False
    ).select_related('school')

    for user in users_with_school:
        Membership.objects.get_or_create(
            user=user,
            school=user.school,
            defaults={
                'role': user.role,
                'job_title': getattr(user, 'job_title', '') or '',
                'is_default': True,
                'is_active': user.is_active,
            },
        )


def backfill_staff_permissions(apps, schema_editor):
    """Relie chaque StaffPermission au Membership correspondant (user + école)."""
    StaffPermission = apps.get_model('accounts', 'StaffPermission')
    Membership = apps.get_model('accounts', 'Membership')

    for sp in StaffPermission.objects.select_related('user'):
        if sp.membership_id:
            continue  # déjà relié
        if sp.user.school_id:
            membership = Membership.objects.filter(
                user=sp.user,
                school_id=sp.user.school_id,
            ).first()
            if membership:
                sp.membership = membership
                sp.save(update_fields=['membership'])


def backfill_enrollments(apps, schema_editor):
    """Crée une StudentEnrollment 'active' par élève actif rattaché à une classe."""
    Student = apps.get_model('students', 'Student')
    StudentEnrollment = apps.get_model('students', 'StudentEnrollment')
    SchoolYear = apps.get_model('schools', 'SchoolYear')

    students = Student.objects.filter(
        is_active=True,
        school__isnull=False,
        school_class__isnull=False,
    ).select_related('school', 'school_class')

    for student in students:
        active_year = SchoolYear.objects.filter(
            school=student.school,
            is_active=True,
        ).first()

        # enrolled_at sur Student est un DateTimeField ; la cible est un DateField.
        enrolled_date = student.enrolled_at.date() if student.enrolled_at else None

        StudentEnrollment.objects.get_or_create(
            student=student,
            school=student.school,
            school_class=student.school_class,
            defaults={
                'school_year': active_year,
                'status': 'active',
                'enrolled_at': enrolled_date,
            },
        )


def noop(apps, schema_editor):
    """Reverse : aucune destruction de données (rollback géré par les migrations schéma)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_membership_promoter_role'),
        # StudentEnrollment vit dans students ; cette dépendance garantit que
        # le modèle existe (et amène schools transitivement).
        ('students', '0004_add_guardian_enrollment'),
    ]

    operations = [
        migrations.RunPython(backfill_memberships,       noop),
        migrations.RunPython(backfill_staff_permissions, noop),
        migrations.RunPython(backfill_enrollments,       noop),
    ]
