# Generated by Django 5.1.15 on 2026-06-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_memberships_phase_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpermission',
            name='can_manage_accounting',
            field=models.BooleanField(default=False, verbose_name='gérer la comptabilité'),
        ),
    ]
