# Generated by Django 5.1.15 on 2026-06-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_can_manage_accounting'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpermission',
            name='can_record_emargement',
            field=models.BooleanField(default=False, verbose_name='émarger les enseignants'),
        ),
    ]
