# Generated by Django 5.1.15 on 2026-06-27 16:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0015_add_school_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex : Inscription, Cantine, Bus, Tenue, Fournitures', max_length=100, verbose_name='nom')),
                ('category', models.CharField(choices=[('one_time', 'Frais ponctuel'), ('tuition', 'Scolarité'), ('subscription', 'Abonnement')], default='one_time', max_length=20, verbose_name='catégorie')),
                ('default_amount', models.DecimalField(blank=True, decimal_places=0, help_text='Laisser vide pour la scolarité et les frais à variantes.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant (FCFA)')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Appliqué automatiquement à tous les élèves.', verbose_name='obligatoire')),
                ('has_variants', models.BooleanField(default=False, help_text="Le montant dépend d'une option (trajet, genre, formule).", verbose_name='à variantes')),
                ('is_gender_based', models.BooleanField(default=False, help_text="La variante est choisie automatiquement selon le genre de l'élève.", verbose_name='selon le genre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='schools.school', verbose_name='école')),
            ],
            options={
                'verbose_name': 'type de frais',
                'verbose_name_plural': 'types de frais',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex : Badalabougou, Fille, Garçon, Repas complet', max_length=100, verbose_name='libellé')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant (FCFA)')),
                ('gender_key', models.CharField(blank=True, max_length=1, null=True, verbose_name='genre')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='finance.feetype', verbose_name='type de frais')),
            ],
            options={
                'verbose_name': 'variante de frais',
                'verbose_name_plural': 'variantes de frais',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PaymentScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex : Annuel, Trimestriel, Mensuel', max_length=50, verbose_name='nom')),
                ('installments_count', models.PositiveSmallIntegerField(help_text='1 = paiement unique, 3 = trimestriel, 9 = mensuel…', validators=[django.core.validators.MinValueValidator(1)], verbose_name='nombre de tranches')),
                ('is_default', models.BooleanField(default=False, verbose_name='par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='schools.school', verbose_name='école')),
            ],
            options={
                'verbose_name': 'gabarit de tranches',
                'verbose_name_plural': 'gabarits de tranches',
                'ordering': ['installments_count'],
            },
        ),
        migrations.AddIndex(
            model_name='feetype',
            index=models.Index(fields=['school', 'is_active'], name='feetype_school_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='feetype',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_fee_type_school_name'),
        ),
        migrations.AddIndex(
            model_name='feevariant',
            index=models.Index(fields=['fee_type', 'is_active'], name='feevariant_type_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentscheduletemplate',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_schedule_template_school_name'),
        ),
        migrations.AddConstraint(
            model_name='paymentscheduletemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('school',), name='uniq_default_schedule_per_school'),
        ),
    ]
