# Generated by Django 5.1.15 on 2026-06-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feevariant',
            constraint=models.UniqueConstraint(fields=('fee_type', 'label'), name='uniq_fee_variant_type_label'),
        ),
    ]
