# Generated by Django 5.1.15 on 2026-06-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_feevariant_uniq_fee_variant_type_label'),
        ('schools', '0015_add_school_announcement'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feetype',
            name='uniq_fee_type_school_name',
        ),
        migrations.RemoveConstraint(
            model_name='feevariant',
            name='uniq_fee_variant_type_label',
        ),
        migrations.AddConstraint(
            model_name='feetype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'name'), name='uniq_active_fee_type_school_name'),
        ),
        migrations.AddConstraint(
            model_name='feevariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('fee_type', 'label'), name='uniq_active_fee_variant_type_label'),
        ),
    ]
