# Generated by Django 5.1.15 on 2026-06-27 18:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_feetype_uniq_fee_type_school_name_and_more'),
        ('payments', '0004_remove_orphan_payment_type_column'),
        ('students', '0007_backfill_active_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='applies_to',
            field=models.CharField(choices=[('new', 'Nouveaux élèves'), ('returning', 'Anciens élèves'), ('all', 'Tous')], default='all', max_length=10, verbose_name="s'applique à"),
        ),
        migrations.AddField(
            model_name='feetype',
            name='returning_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Montant réduit pour les anciens élèves. Vide = même tarif pour tous.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tarif réinscription (FCFA)'),
        ),
        migrations.CreateModel(
            name='FeeDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tuition', 'Scolarité'), ('one_time', 'Frais ponctuel'), ('subscription', 'Abonnement')], max_length=20, verbose_name='famille')),
                ('label', models.CharField(max_length=150, verbose_name='libellé')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant total (FCFA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('fee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='finance.feetype', verbose_name='type de frais')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='finance.feevariant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'dette',
                'verbose_name_plural': 'dettes',
                'ordering': ['kind', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=1, verbose_name='ordre')),
                ('amount_due', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant attendu (FCFA)')),
                ('due_date', models.DateField(verbose_name='date limite')),
                ('label', models.CharField(max_length=100, verbose_name='libellé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.feedebt', verbose_name='dette')),
            ],
            options={
                'verbose_name': 'tranche',
                'verbose_name_plural': 'tranches',
                'ordering': ['debt', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='montant affecté (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.installment', verbose_name='tranche')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.payment', verbose_name='paiement')),
            ],
            options={
                'verbose_name': 'allocation de paiement',
                'verbose_name_plural': 'allocations de paiement',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_account', to='students.studentenrollment', verbose_name='inscription')),
            ],
            options={
                'verbose_name': 'fiche financière',
                'verbose_name_plural': 'fiches financières',
            },
        ),
        migrations.AddField(
            model_name='feedebt',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='finance.studentfeeaccount', verbose_name='fiche'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['due_date'], name='installment_due_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('debt', 'sequence'), name='uniq_installment_debt_sequence'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment'], name='alloc_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['installment'], name='alloc_installment_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='paymentallocation_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='feedebt',
            index=models.Index(fields=['account', 'kind'], name='feedebt_account_kind_idx'),
        ),
    ]
