# Generated by Django 5.1.15 on 2026-07-07 18:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_feetype_applies_to_feetype_returning_amount_feedebt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('discount', 'Remise')], default='discount', max_length=20, verbose_name='type')),
                ('motif', models.CharField(choices=[('fratrie', 'Fratrie'), ('staff', 'Enfant du personnel'), ('merit', 'Bourse / mérite'), ('social', 'Cas social'), ('relation', 'Gratuité famille / relation'), ('girl', 'Scolarisation fille'), ('early', 'Paiement anticipé'), ('gesture', 'Geste commercial'), ('other', 'Autre')], max_length=20, verbose_name='motif')),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='pourcentage')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant fixe (FCFA)')),
                ('resolved_amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant de la remise (FCFA)')),
                ('funding_source', models.CharField(choices=[('school', 'École'), ('donor', 'Donateur'), ('promoter', 'Promoteur')], default='school', max_length=20, verbose_name='financé par')),
                ('justification', models.TextField(blank=True, verbose_name='justification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='accordée le')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='annulée')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulée le')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_adjustments_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='annulée par')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_adjustments_created', to=settings.AUTH_USER_MODEL, verbose_name='accordée par')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='finance.feedebt', verbose_name='dette')),
            ],
            options={
                'verbose_name': 'remise',
                'verbose_name_plural': 'remises',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['debt', 'is_cancelled'], name='adjustment_debt_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('amount__isnull', True), ('percent__isnull', False)), models.Q(('amount__isnull', False), ('percent__isnull', True)), _connector='OR'), name='adjustment_percent_xor_amount')],
            },
        ),
    ]
