# Generated by Django 5.1.15 on 2026-07-07 20:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_feeadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='applies_to_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('prescolaire', 'Préscolaire'), ('fondamental_1', 'Fondamental 1er Cycle'), ('fondamental_2', 'Fondamental 2ème Cycle'), ('secondaire_gen', 'Secondaire Général'), ('secondaire_pro', 'Secondaire Professionnel'), ('superieur', 'Enseignement Supérieur')], max_length=20), blank=True, default=list, size=None, verbose_name='niveaux concernés'),
        ),
    ]
