# Generated by Django 5.1.15 on 2026-07-08 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_feetype_applies_to_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentscheduletemplate',
            name='installments_count',
            field=models.PositiveSmallIntegerField(help_text='Entre 1 et 12. Ex : 1 = paiement unique, 3 = trimestriel, 9 = mensuel…', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='nombre de tranches'),
        ),
    ]
