# Generated by Django 6.0.6 on 2026-06-09 19:53

import apps.students.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='nom complet')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='téléphone élève')),
                ('parent_phone_number', models.CharField(blank=True, max_length=20, verbose_name='téléphone parent')),
                ('access_code', models.CharField(default=apps.students.models.generate_student_access_code, editable=False, max_length=8, unique=True, verbose_name="code d'accès")),
                ('tuition_fee', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='frais de scolarité (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='informations supplémentaires')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='inscrit le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school', verbose_name='école')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='schools.schoolclass', verbose_name='classe')),
            ],
            options={
                'verbose_name': 'élève',
                'verbose_name_plural': 'élèves',
                'ordering': ['full_name'],
            },
        ),
    ]
