# Generated by Django 6.0.6 on 2026-06-09 23:38

import random
import apps.students.models
from django.db import migrations, models


def regenerate_access_codes(apps, schema_editor):
    """Convertit les codes existants (8 hex) en codes à 6 chiffres avant réduction de max_length."""
    Student = apps.get_model('students', 'Student')
    used = {}
    for student in Student.objects.select_related('school').order_by('id'):
        school_id = student.school_id
        if school_id not in used:
            used[school_id] = set(
                Student.objects.filter(school_id=school_id)
                .exclude(pk=student.pk)
                .values_list('access_code', flat=True)
            )
        code = str(random.randint(100000, 999999))
        while code in used[school_id]:
            code = str(random.randint(100000, 999999))
        used[school_id].add(code)
        student.access_code = code
        student.save(update_fields=['access_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_relationship',
            field=models.CharField(blank=True, choices=[('father', 'Père'), ('mother', 'Mère'), ('guardian', 'Tuteur/Tutrice')], max_length=10, verbose_name='lien de parenté'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='nom complet'),
        ),
        # Migrer les codes AVANT de réduire max_length (8→6) — sinon PostgreSQL rejette
        migrations.RunPython(regenerate_access_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student',
            name='access_code',
            field=models.CharField(default=apps.students.models.generate_student_access_code, editable=False, max_length=6, verbose_name="code d'accès"),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'access_code')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'school_class'], name='student_school_class_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'is_active'], name='student_school_active_idx'),
        ),
    ]
