# Generated by Django 5.1.15 on 2026-06-11 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_fix_protect_and_unique_constraints'),
        ('students', '0002_student_v2_access_code_parent_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='schools.school', verbose_name='école'),
        ),
    ]
