# Generated by Django 5.1.15 on 2026-06-13 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_add_school_group'),
        ('students', '0003_fix_protect_and_unique_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_relationship',
            field=models.CharField(blank=True, choices=[('father', 'Père'), ('mother', 'Mère'), ('guardian', 'Tuteur/Tutrice'), ('other', 'Autre')], max_length=10, verbose_name='lien de parenté'),
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'En cours'), ('transferred', 'Transféré'), ('graduated', 'Diplômé / Passé'), ('withdrawn', 'Retiré')], default='active', max_length=20, verbose_name='statut')),
                ('enrolled_at', models.DateField(blank=True, null=True, verbose_name='inscrit le')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='terminé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='schools.school', verbose_name='école')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='schools.schoolclass', verbose_name='classe')),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='schools.schoolyear', verbose_name='année scolaire')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student', verbose_name='élève')),
            ],
            options={
                'verbose_name': 'inscription',
                'verbose_name_plural': 'inscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='enrollment_student_status_idx'), models.Index(fields=['school', 'school_year'], name='enrollment_school_year_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, choices=[('father', 'Père'), ('mother', 'Mère'), ('guardian', 'Tuteur/Tutrice'), ('other', 'Autre')], max_length=10, verbose_name='lien de parenté')),
                ('is_primary', models.BooleanField(default=False, verbose_name='contact principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarded_students', to=settings.AUTH_USER_MODEL, verbose_name='parent / tuteur')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student', verbose_name='élève')),
            ],
            options={
                'verbose_name': "parent d'élève",
                'verbose_name_plural': "parents d'élèves",
                'indexes': [models.Index(fields=['guardian'], name='guardian_idx'), models.Index(fields=['student'], name='guardian_student_idx')],
                'constraints': [models.UniqueConstraint(fields=('guardian', 'student'), name='unique_guardian_student')],
            },
        ),
    ]
