# Generated by Django 5.1.15 on 2026-06-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_add_guardian_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='badges',
            field=models.JSONField(default=list, verbose_name='badges'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='niveau'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True, verbose_name='dernière activité'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dernière connexion'),
        ),
        migrations.AddField(
            model_name='student',
            name='longest_streak',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='meilleur streak'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, help_text='Hash du mot de passe élève', max_length=128, verbose_name='mot de passe'),
        ),
        migrations.AddField(
            model_name='student',
            name='streak_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='streak jours'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_xp',
            field=models.PositiveIntegerField(default=0, verbose_name='XP total'),
        ),
    ]
