# Generated by Django 5.1.15 on 2026-06-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_add_school_announcement'),
        ('students', '0005_add_student_auth_gamification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Garçon'), ('F', 'Fille')], max_length=1, null=True, verbose_name='genre'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('school_year__isnull', False)), fields=('student', 'school_year'), name='uniq_enrollment_student_year'),
        ),
    ]
