# Generated by Django 5.1.15 on 2026-07-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0025_remove_period_uniq_period_year_name_nocycle_and_more'),
        ('students', '0007_backfill_active_enrollments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'élève', 'verbose_name_plural': 'élèves'},
        ),
        migrations.AddField(
            model_name='student',
            name='birth_place',
            field=models.CharField(blank=True, max_length=120, verbose_name='lieu de naissance'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='prénom(s)'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='nom de famille'),
        ),
        migrations.AddField(
            model_name='student',
            name='matricule',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='matricule'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='nom complet (auto)'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('matricule__gt', '')), fields=('school', 'matricule'), name='uniq_matricule_per_school'),
        ),
    ]
