# Generated by Django 5.1.15 on 2026-07-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_options_student_birth_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
    ]
