# Generated by Django 5.1.15 on 2026-07-07 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_guardian_info(apps, schema_editor):
    """Responsables déjà liés : copier nom/téléphone depuis leur compte pour l'affichage."""
    SG = apps.get_model('students', 'StudentGuardian')
    for sg in SG.objects.filter(guardian__isnull=False).select_related('guardian'):
        updates = {}
        if not sg.full_name and sg.guardian.full_name:
            updates['full_name'] = sg.guardian.full_name
        if not sg.phone and sg.guardian.phone_number:
            updates['phone'] = sg.guardian.phone_number
        if updates:
            for k, v in updates.items():
                setattr(sg, k, v)
            sg.save(update_fields=list(updates))


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_student_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_relationship',
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='nom du responsable'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='studentguardian',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guarded_students', to=settings.AUTH_USER_MODEL, verbose_name='compte portail (optionnel)'),
        ),
        migrations.RunPython(backfill_guardian_info, migrations.RunPython.noop),
    ]
