# Generated by Django 5.1.15 on 2026-07-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_remove_student_parent_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentguardian',
            name='email',
        ),
    ]
