# Generated by Django 5.1.15 on 2026-06-14 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial_lessons_models'),
        ('students', '0005_add_student_auth_gamification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='% bonnes réponses')),
                ('answers', models.JSONField(default=list)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_attempts', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_attempts', to='students.student')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('challenge_type', models.CharField(choices=[('quiz_daily', 'Quiz du jour'), ('flashcard_review', 'Révision flashcards'), ('lesson_read', 'Lire une leçon'), ('story_complete', 'Compléter une story')], max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('xp_earned', models.PositiveSmallIntegerField(default=0)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_challenges', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'date', 'is_completed'], name='challenge_student_date_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashcard_id', models.CharField(max_length=20)),
                ('ease_factor', models.DecimalField(decimal_places=2, default=2.5, max_digits=4)),
                ('interval_days', models.PositiveSmallIntegerField(default=1)),
                ('repetitions', models.PositiveSmallIntegerField(default=0)),
                ('next_review_date', models.DateField(default=django.utils.timezone.localdate)),
                ('last_quality', models.PositiveSmallIntegerField(blank=True, help_text='0-5, dernière réponse', null=True)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_flashcards', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'next_review_date'], name='flash_student_review_idx')],
                'unique_together': {('student', 'lesson', 'flashcard_id')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_block_index', models.PositiveIntegerField(default=0)),
                ('reading_time_seconds', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.JSONField(default=list, help_text='Notes perso : [{block_id, text, created_at}]')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progresses', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'is_completed'], name='progress_student_done_idx')],
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=20)),
                ('question_type', models.CharField(max_length=30)),
                ('student_answer', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('time_spent_seconds', models.PositiveSmallIntegerField(default=0)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'lesson'], name='quiz_student_lesson_idx'), models.Index(fields=['student', 'is_correct'], name='quiz_student_correct_idx'), models.Index(fields=['student', 'attempted_at'], name='quiz_student_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(choices=[('primaire', 'Primaire'), ('secondaire', 'Secondaire'), ('superieur', 'Supérieur / Prépa')], max_length=20, verbose_name='niveau')),
                ('subscription_type', models.CharField(choices=[('free', 'Gratuit'), ('premium', 'Premium'), ('prepa', 'Prépa Examen')], default='free', max_length=20, verbose_name='type')),
                ('price_paid', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='montant payé (FCFA)')),
                ('start_date', models.DateField(verbose_name='début')),
                ('end_date', models.DateField(verbose_name='fin')),
                ('payment_method', models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('moov', 'Moov Money'), ('wave', 'Wave'), ('cash', 'Espèces'), ('other', 'Autre')], max_length=20, verbose_name='mode paiement')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='référence paiement')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='activé par')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='students.student', verbose_name='élève')),
            ],
            options={
                'verbose_name': 'abonnement élève',
                'verbose_name_plural': 'abonnements élèves',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'is_active'], name='sub_student_active_idx'), models.Index(fields=['end_date'], name='sub_end_date_idx')],
            },
        ),
    ]
