# Generated by Django 5.1.15 on 2026-06-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_learning', '0001_initial_student_learning_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='quiz_bonus_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
