# Generated by Django 5.1.15 on 2026-06-24 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lessoncontentversion'),
        ('student_learning', '0002_add_quiz_bonus_awarded'),
        ('students', '0005_add_student_auth_gamification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.CharField(max_length=50)),
                ('passes_done', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concept_progresses', to='lessons.lessoncontentversion')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_progresses', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_progresses', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'lesson'], name='cprog_student_lesson_idx')],
                'unique_together': {('student', 'content_version', 'concept_id')},
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('pass_mark', models.FloatField(help_text='Seuil de réussite, gelé au moment de la tentative')),
                ('score', models.FloatField(default=0, help_text='Fraction 0..1, dérivée de answers')),
                ('passed', models.BooleanField(default=False)),
                ('answers', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('content_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_attempts', to='lessons.lessoncontentversion')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='students.student')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', 'lesson'], name='exam_student_lesson_idx'), models.Index(fields=['student', 'content_version'], name='exam_student_version_idx')],
            },
        ),
    ]
