# Generated by Django 5.1.15 on 2026-06-24 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lessoncontentversion'),
        ('student_learning', '0003_exam_concept_progress'),
        ('students', '0005_add_student_auth_gamification'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=20)),
                ('variables', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_draws', to='lessons.lessoncontentversion')),
                ('exam_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_draws', to='student_learning.examattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_draws', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'content_version', 'quiz_id'], name='draw_practice_lookup_idx'), models.Index(fields=['exam_attempt'], name='draw_exam_attempt_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('exam_attempt__isnull', False)), fields=('exam_attempt', 'quiz_id'), name='uniq_exam_draw')],
            },
        ),
    ]
