# Generated by Django 5.1.15 on 2026-06-24 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lessoncontentversion'),
        ('student_learning', '0004_questiondraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='content_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz_attempts', to='lessons.lessoncontentversion'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='draw_variables',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
