# Generated by Django 5.1.15 on 2026-06-26 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_unit_generation_lock'),
        ('student_learning', '0005_quizattempt_v2_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyattempt',
            name='content_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='story_attempts', to='lessons.lessoncontentversion'),
        ),
    ]
