# Generated by Django 5.1.15 on 2026-06-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_learning', '0006_storyattempt_content_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyChallenge',
        ),
    ]
