# Generated by Django 5.1.15 on 2026-06-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_learning', '0007_delete_dailychallenge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentSubscription',
        ),
    ]
