# Generated by Django 5.1.15 on 2026-06-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_learning', '0008_delete_studentsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flashcard',
        ),
    ]
