# Generated by Django 5.1.15 on 2026-07-10 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_lessoncontentdraft_ai_flags'),
        ('student_learning', '0010_studentnote'),
        ('students', '0011_remove_studentguardian_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='source',
            field=models.CharField(default='parcours', max_length=12),
        ),
        migrations.CreateModel(
            name='ConceptReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.CharField(max_length=50)),
                ('box', models.PositiveSmallIntegerField(default=1)),
                ('due_date', models.DateField()),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concept_reviews', to='lessons.lessoncontentversion')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_reviews', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_reviews', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'due_date'], name='creview_student_due_idx')],
                'unique_together': {('student', 'content_version', 'concept_id')},
            },
        ),
    ]
