# Generated by Django 5.1.15 on 2026-07-10 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_lessoncontentdraft_ai_flags'),
        ('student_learning', '0011_quizattempt_source_conceptreview'),
        ('students', '0011_remove_studentguardian_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CahierAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField(default=list)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('content_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cahier_attempts', to='lessons.lessoncontentversion')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cahier_attempts', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cahier_attempts', to='students.student')),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['student', 'content_version'], name='cahier_student_ver_idx')],
            },
        ),
    ]
