# Generated by Django 5.1.15 on 2026-06-14 06:40

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_add_can_manage_accounting'),
        ('schools', '0013_add_duration_hours_accounting_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent (salaire fixe)'), ('vacataire', "Vacataire (à l'heure)")], default='permanent', max_length=20, verbose_name="type d'emploi")),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=0, help_text='Pour les permanents', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='salaire mensuel (FCFA)')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=0, help_text='Pour les vacataires', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='taux horaire (FCFA)')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name="date d'embauche")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to='accounts.membership', verbose_name='appartenance')),
            ],
            options={
                'verbose_name': 'profil employé',
                'verbose_name_plural': 'profils employés',
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='icône Lucide')),
                ('is_default', models.BooleanField(default=False, verbose_name='prédéfinie')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='schools.school', verbose_name='école')),
            ],
            options={
                'verbose_name': 'catégorie de dépense',
                'verbose_name_plural': 'catégories de dépense',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='montant (FCFA)')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='description')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='mode de paiement')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='annulée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL, verbose_name='enregistré par')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='schools.school', verbose_name='école')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounting.expensecategory', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'dépense',
                'verbose_name_plural': 'dépenses',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['school', 'date'], name='expense_school_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='année')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='mois')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant (FCFA)')),
                ('hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='heures')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='taux horaire (FCFA)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé')], default='pending', max_length=10, verbose_name='statut')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='mode de paiement')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='payé le')),
                ('employee_name', models.CharField(blank=True, max_length=150, verbose_name='nom employé (snapshot)')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='annulé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='accounts.membership', verbose_name='employé')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_salaries', to=settings.AUTH_USER_MODEL, verbose_name='payé par')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='schools.school', verbose_name='école')),
            ],
            options={
                'verbose_name': 'paie',
                'verbose_name_plural': 'paies',
                'ordering': ['-year', '-month', 'employee_name'],
                'indexes': [models.Index(fields=['school', 'year', 'month'], name='salary_school_period_idx'), models.Index(fields=['status'], name='salary_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cancelled', False)), fields=('employee', 'year', 'month'), name='uniq_salary_employee_month')],
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('status', models.CharField(choices=[('present', 'Présent (cours assuré)'), ('absent', 'Absent (cours non assuré)'), ('replaced', 'Remplacé')], default='present', max_length=10, verbose_name='statut')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='émargé le')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_attendances', to='schools.classsubject', verbose_name='cours')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_teacher_attendances', to=settings.AUTH_USER_MODEL, verbose_name='enregistré par')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendances', to='schools.school', verbose_name='école')),
                ('substitute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_attendances', to=settings.AUTH_USER_MODEL, verbose_name='remplaçant')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_attendances', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
            ],
            options={
                'verbose_name': 'émargement enseignant',
                'verbose_name_plural': 'émargements enseignants',
                'ordering': ['-date', 'class_subject'],
                'indexes': [models.Index(fields=['school', 'date'], name='tatt_school_date_idx'), models.Index(fields=['teacher', 'date'], name='tatt_teacher_date_idx'), models.Index(fields=['substitute', 'date'], name='tatt_sub_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('class_subject', 'date'), name='uniq_teacher_att_course_date')],
            },
        ),
    ]
