# Generated by Django 5.1.15 on 2026-06-14 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial_accounting_models'),
        ('schools', '0013_add_duration_hours_accounting_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherattendance',
            name='uniq_teacher_att_course_date',
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='session',
            field=models.CharField(choices=[('morning', 'Matin'), ('afternoon', 'Après-midi'), ('full', 'Journée entière')], default='morning', max_length=10, verbose_name='session'),
        ),
        migrations.AddConstraint(
            model_name='teacherattendance',
            constraint=models.UniqueConstraint(fields=('class_subject', 'date', 'session'), name='uniq_tatt_course_date_session'),
        ),
    ]
