# Generated by Django 5.1.15 on 2026-06-14 07:42
#
# Seed des 12 catégories de dépense globales (school=NULL, is_default=True).
# Idempotent (get_or_create) + réversible (suppression des catégories par défaut).

from django.db import migrations

CATEGORIES = [
    ('Loyer', 'home'),
    ('Électricité', 'zap'),
    ('Eau', 'droplets'),
    ('Internet / Téléphone', 'wifi'),
    ('Fournitures scolaires', 'book'),
    ('Matériel de bureau', 'printer'),
    ("Produits d'entretien", 'spray-can'),
    ('Transport / Carburant', 'car'),
    ('Réparations / Maintenance', 'wrench'),
    ('Événements scolaires', 'party-popper'),
    ('Frais administratifs', 'file-check'),
    ('Autre', 'more-horizontal'),
]


def seed_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model('accounting', 'ExpenseCategory')
    for name, icon in CATEGORIES:
        ExpenseCategory.objects.get_or_create(
            school=None, name=name,
            defaults={'icon': icon, 'is_default': True, 'is_active': True},
        )


def unseed_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model('accounting', 'ExpenseCategory')
    ExpenseCategory.objects.filter(
        school__isnull=True, is_default=True,
        name__in=[c[0] for c in CATEGORIES],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_add_session_to_teacher_attendance'),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
