# Generated by Django 5.1.15 on 2026-06-16 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_seed_expense_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name="motif d'annulation"),
        ),
        migrations.AddField(
            model_name='expense',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='annulée le'),
        ),
        migrations.AddField(
            model_name='expense',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_expenses', to=settings.AUTH_USER_MODEL, verbose_name='annulée par'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name="motif d'annulation"),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='annulé le'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_salaries', to=settings.AUTH_USER_MODEL, verbose_name='annulé par'),
        ),
    ]
