# Generated by Django 5.1.15 on 2026-06-30 10:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_expense_cancellation_reason_expense_cancelled_at_and_more'),
        ('schools', '0017_evaluationcolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacataireRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='taux horaire (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacataire_rates', to='schools.classsubject', verbose_name='cours')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_rates', to='accounting.employeeprofile', verbose_name='profil employé')),
            ],
            options={
                'verbose_name': 'tarif vacataire',
                'verbose_name_plural': 'tarifs vacataire',
                'constraints': [models.UniqueConstraint(fields=('profile', 'class_subject'), name='uniq_vacataire_rate_course')],
            },
        ),
    ]
