# Generated by Django 5.1.15 on 2026-06-30 12:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_vacatairerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Si vide, la durée prévue du cours est utilisée. Permet le « partiel ».', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))], verbose_name='heures réelles'),
        ),
    ]
