# Generated by Django 5.1.15 on 2026-06-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_teacherattendance_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='absence_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='absences retenues'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='deduction',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='retenue (FCFA)'),
        ),
    ]
