# Generated by Django 5.1.15 on 2026-06-30 15:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_salarypayment_absence_count_salarypayment_deduction'),
        ('schools', '0018_school_absence_deduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='libellé')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='montant (FCFA)')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='mode de paiement')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='accounting.expensecategory', verbose_name='catégorie')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to='schools.school', verbose_name='école')),
            ],
            options={
                'verbose_name': 'dépense récurrente',
                'verbose_name_plural': 'dépenses récurrentes',
                'ordering': ['category__name', 'label'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='accounting.recurringexpense', verbose_name='dépense récurrente'),
        ),
    ]
