# Generated by Django 5.1.15 on 2026-07-12 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_recurringexpense_expense_recurring'),
        ('schools', '0028_remove_classsubject_duration_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherattendance',
            name='uniq_tatt_course_date_session',
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='session',
        ),
        migrations.AddConstraint(
            model_name='teacherattendance',
            constraint=models.UniqueConstraint(fields=('class_subject', 'date'), name='uniq_tatt_course_date'),
        ),
    ]
