# Generated by Django 5.1.15 on 2026-07-12 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_remove_teacherattendance_uniq_tatt_course_date_session_and_more'),
        ('schools', '0028_remove_classsubject_duration_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherattendance',
            name='uniq_tatt_course_date',
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='schools.courseslot', verbose_name='créneau'),
        ),
        migrations.AddConstraint(
            model_name='teacherattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('slot__isnull', False)), fields=('slot', 'date'), name='uniq_tatt_slot_date'),
        ),
        migrations.AddConstraint(
            model_name='teacherattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('slot__isnull', True)), fields=('class_subject', 'date'), name='uniq_tatt_course_date_noslot'),
        ),
    ]
