# Generated by Django 6.0.6 on 2026-06-09 19:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='montant versé (FCFA)')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque')], default='cash', max_length=20, verbose_name='mode de paiement')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='date du versement')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='numéro de reçu')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_valid', models.BooleanField(default=True, verbose_name='valide')),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collected_payments', to=settings.AUTH_USER_MODEL, verbose_name='encaissé par')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student', verbose_name='élève')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-paid_at'],
            },
        ),
    ]
