# Generated by Django 6.0.6 on 2026-06-10 10:04

import datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('students', '0002_student_v2_access_code_parent_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name': 'paiement', 'verbose_name_plural': 'paiements'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name="motif d'annulation"),
        ),
        migrations.AddField(
            model_name='payment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='annulé le'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='annulé'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='date du versement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='mode de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='numéro de reçu'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'is_cancelled'], name='payments_pa_student_d80011_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'),
        ),
    ]
