# Generated by Django 5.1.15 on 2026-06-11 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_fields_update'),
        ('students', '0002_student_v2_access_code_parent_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='students.student', verbose_name='élève'),
        ),
    ]
