# Generated by Django 5.1.15 on 2026-06-13 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0011_add_composite_indexes'),
        ('students', '0003_fix_protect_and_unique_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('status', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('late', 'En retard')], default='present', max_length=10, verbose_name='statut')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='enregistré le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='schools.school', verbose_name='école')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='schools.schoolclass', verbose_name='classe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='élève')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_recorded', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
            ],
            options={
                'verbose_name': 'présence',
                'verbose_name_plural': 'présences',
                'ordering': ['-date', 'student__full_name'],
                'indexes': [models.Index(fields=['school', 'school_class', 'date'], name='att_school_cls_date_idx'), models.Index(fields=['student', 'date'], name='attendance_student_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('school_class', 'student', 'date'), name='unique_attendance_per_student_date')],
            },
        ),
        migrations.CreateModel(
            name='StudentObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_type', models.CharField(choices=[('behaviour', 'Comportement'), ('academic', 'Académique'), ('health', 'Santé'), ('other', 'Autre')], default='academic', max_length=20, verbose_name='type')),
                ('content', models.TextField(verbose_name='contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='rédigée le')),
                ('is_read', models.BooleanField(default=False, verbose_name='lue par admin')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lue le')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations_read', to=settings.AUTH_USER_MODEL, verbose_name='lue par')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='schools.school', verbose_name='école')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='students.student', verbose_name='élève')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_written', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
            ],
            options={
                'verbose_name': 'observation',
                'verbose_name_plural': 'observations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'is_read'], name='observation_school_read_idx'), models.Index(fields=['student', 'teacher'], name='obs_student_teacher_idx')],
            },
        ),
    ]
