# Generated by Django 5.1.15 on 2026-06-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_attendance_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentobservation',
            name='is_private',
            field=models.BooleanField(default=True, verbose_name='note privée'),
        ),
    ]
