# Generated by Django 5.1.15 on 2026-06-13 15:22

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_add_composite_indexes'),
        ('students', '0003_fix_protect_and_unique_constraints'),
        ('teachers', '0002_add_observation_privacy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('oral', 'Interrogation orale'), ('written', 'Petit contrôle écrit'), ('homework', 'Devoir maison'), ('classwork', 'Travail en classe'), ('behavior', 'Comportement / Participation')], default='oral', max_length=20, verbose_name='type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='note obtenue')),
                ('max_value', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='note maximale')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='remarque')),
                ('assessed_at', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quick_assessments', to='schools.classsubject', verbose_name='matière de classe')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quick_assessments', to='schools.period', verbose_name='période')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quick_assessments', to='students.student', verbose_name='élève')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_assessments', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
            ],
            options={
                'verbose_name': 'évaluation rapide',
                'verbose_name_plural': 'évaluations rapides',
                'ordering': ['-assessed_at', '-created_at'],
                'indexes': [models.Index(fields=['teacher', 'student', 'period'], name='qa_teacher_student_per_idx'), models.Index(fields=['class_subject', 'period'], name='qa_cs_period_idx')],
            },
        ),
    ]
