# Generated by Django 5.1.15 on 2026-06-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_add_quick_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentobservation',
            name='is_visible_to_parent',
            field=models.BooleanField(default=False, help_text="Coché par l'admin pour partager avec les parents de l'élève", verbose_name='visible par le parent'),
        ),
        migrations.AddField(
            model_name='studentobservation',
            name='parent_message',
            field=models.TextField(blank=True, help_text='Message reformulé pour le parent (optionnel)', verbose_name='message pour le parent'),
        ),
    ]
