# Generated by Django 6.0.6 on 2026-06-09 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="nom de l'école")),
                ('city', models.CharField(max_length=100, verbose_name='ville')),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100, verbose_name='pays')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('logo', models.ImageField(blank=True, upload_to='schools/logos/', verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
            ],
            options={
                'verbose_name': 'école',
                'verbose_name_plural': 'écoles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom de la classe')),
                ('level', models.CharField(choices=[('primary', 'Primaire'), ('middle', 'Collège'), ('high', 'Lycée'), ('university', 'Université')], max_length=20, verbose_name='niveau')),
                ('annual_fee', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='frais de scolarité annuels (FCFA)')),
                ('max_capacity', models.PositiveSmallIntegerField(blank=True, help_text='Laisser vide si pas de limite', null=True, verbose_name='capacité maximale')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school', verbose_name='école')),
            ],
            options={
                'verbose_name': 'classe',
                'verbose_name_plural': 'classes',
                'ordering': ['level', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
    ]
