# Generated by Django 6.0.6 on 2026-06-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='adresse'),
        ),
        migrations.AddField(
            model_name='school',
            name='current_school_year',
            field=models.CharField(blank=True, help_text='Ex : 2024-2025', max_length=20, verbose_name='année scolaire en cours'),
        ),
        migrations.AddField(
            model_name='school',
            name='primary_color',
            field=models.CharField(default='#1E3A5F', help_text='Code hexadécimal, ex : #1E3A5F', max_length=7, verbose_name='couleur principale'),
        ),
        migrations.AddField(
            model_name='school',
            name='receipt_configured_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reçu configuré le'),
        ),
        migrations.AddField(
            model_name='school',
            name='receipt_mapping',
            field=models.JSONField(blank=True, default=dict, verbose_name='mapping variables reçu'),
        ),
        migrations.AddField(
            model_name='school',
            name='receipt_mode',
            field=models.CharField(choices=[('standard', 'Reçu standard EduApp'), ('custom', 'Reçu personnalisé')], default='standard', max_length=10, verbose_name='mode de reçu'),
        ),
        migrations.AddField(
            model_name='school',
            name='receipt_template_pdf',
            field=models.FileField(blank=True, upload_to='schools/receipts/', verbose_name='template reçu PDF'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('mixte', 'Mixte (primaire + collège)'), ('university', 'Université'), ('formation', 'Centre de formation')], default='', max_length=20, verbose_name="type d'établissement"),
        ),
    ]
