# Generated by Django 6.0.6 on 2026-06-10 12:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_settings_fields'),
        ('students', '0002_student_v2_access_code_parent_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='notes_delegates',
            field=models.ManyToManyField(blank=True, related_name='delegate_classes', to=settings.AUTH_USER_MODEL, verbose_name='délégués de saisie'),
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nom')),
                ('start_date', models.DateField(verbose_name='début')),
                ('end_date', models.DateField(verbose_name='fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_years', to='schools.school', verbose_name='école')),
            ],
            options={
                'verbose_name': 'année scolaire',
                'verbose_name_plural': 'années scolaires',
                'ordering': ['-start_date'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('period_type', models.CharField(choices=[('trimester', 'Trimestre'), ('semester', 'Semestre'), ('custom', 'Personnalisé')], default='trimester', max_length=10, verbose_name='type')),
                ('start_date', models.DateField(verbose_name='début')),
                ('end_date', models.DateField(verbose_name='fin')),
                ('is_notes_open', models.BooleanField(default=False, verbose_name='saisie notes ouverte')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ordre')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='schools.schoolyear', verbose_name='année scolaire')),
            ],
            options={
                'verbose_name': 'période',
                'verbose_name_plural': 'périodes',
                'ordering': ['order'],
                'unique_together': {('school_year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('short_name', models.CharField(max_length=10, verbose_name='abréviation')),
                ('color', models.CharField(default='#1E3A5F', max_length=7, verbose_name='couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school', verbose_name='école')),
            ],
            options={
                'verbose_name': 'matière',
                'verbose_name_plural': 'matières',
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='coefficient')),
                ('note_system', models.CharField(choices=[('devoirs_compo', 'Devoirs + Composition'), ('moyenne_simple', 'Moyenne simple')], default='moyenne_simple', max_length=20, verbose_name='système de notes')),
                ('coeff_devoirs', models.DecimalField(decimal_places=2, default=Decimal('0.40'), max_digits=3, verbose_name='coefficient devoirs')),
                ('coeff_compo', models.DecimalField(decimal_places=2, default=Decimal('0.60'), max_digits=3, verbose_name='coefficient composition')),
                ('max_grade', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='note maximale')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='schools.schoolclass', verbose_name='classe')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='schools.subject', verbose_name='matière')),
            ],
            options={
                'verbose_name': 'matière de classe',
                'verbose_name_plural': 'matières de classe',
                'ordering': ['order', 'subject__name'],
                'unique_together': {('school_class', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('devoir', 'Devoir'), ('composition', 'Composition'), ('simple', 'Note simple')], default='simple', max_length=15, verbose_name='type de note')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valeur')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='saisie le')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='annulée')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name="motif d'annulation")),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='schools.classsubject', verbose_name='matière de classe')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_notes', to=settings.AUTH_USER_MODEL, verbose_name='saisie par')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_notes', to=settings.AUTH_USER_MODEL, verbose_name='modifiée par')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_notes', to='students.student', verbose_name='élève')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='schools.period', verbose_name='période')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['-entered_at'],
                'indexes': [models.Index(fields=['student', 'period'], name='note_student_period_idx'), models.Index(fields=['class_subject', 'period'], name='note_cs_period_idx')],
            },
        ),
    ]
