# Generated by Django 6.0.6 on 2026-06-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_grades_foundation'),
        ('students', '0002_student_v2_access_code_parent_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['student__full_name', 'position'], 'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
        migrations.AddField(
            model_name='note',
            name='position',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='position'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('student', 'class_subject', 'period', 'position')},
        ),
    ]
