# Generated by Django 5.1.15 on 2026-06-10 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_note_position'),
        ('students', '0002_student_v2_access_code_parent_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='généré le')),
                ('is_published', models.BooleanField(default=False, verbose_name='publié')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publié le')),
                ('general_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='moyenne générale')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='rang')),
                ('class_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='effectif classe')),
                ('first_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='moyenne du premier')),
                ('appreciation', models.CharField(blank=True, max_length=50, verbose_name='appréciation générale')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='bulletins/%Y/%m/', verbose_name='fichier PDF')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='annulé')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_bulletins', to=settings.AUTH_USER_MODEL, verbose_name='généré par')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='schools.period', verbose_name='période')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='schools.schoolclass', verbose_name='classe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='students.student', verbose_name='élève')),
            ],
            options={
                'verbose_name': 'bulletin',
                'verbose_name_plural': 'bulletins',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='BulletinConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_ministry_header', models.BooleanField(default=True, verbose_name="afficher l'en-tête ministériel")),
                ('ministry_text', models.TextField(blank=True, default='', verbose_name='texte ministère (gauche)')),
                ('republic_text', models.TextField(blank=True, default='', verbose_name='texte république (droite)')),
                ('show_logo', models.BooleanField(default=True, verbose_name='afficher le logo')),
                ('paper_format', models.CharField(choices=[('full_page', 'Pleine page A4'), ('two_per_page', 'Deux par page A4')], default='two_per_page', max_length=15, verbose_name="format d'impression")),
                ('language', models.CharField(choices=[('french', 'Français'), ('arabic', 'Arabe'), ('bilingual', 'Bilingue')], default='french', max_length=10, verbose_name='langue du bulletin')),
                ('show_rank', models.BooleanField(default=True, verbose_name='afficher le classement')),
                ('show_class_average', models.BooleanField(default=True, verbose_name='afficher la moyenne de classe')),
                ('show_first_average', models.BooleanField(default=True, verbose_name='afficher la moyenne du premier')),
                ('show_appreciations', models.BooleanField(default=True, verbose_name='afficher les appréciations')),
                ('footer_left', models.CharField(blank=True, default='Le Parent', max_length=100, verbose_name='pied gauche')),
                ('footer_right', models.CharField(blank=True, default='Le Directeur', max_length=100, verbose_name='pied droit')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_config', to='schools.school', verbose_name='école')),
            ],
            options={
                'verbose_name': 'configuration bulletin',
                'verbose_name_plural': 'configurations bulletin',
            },
        ),
        migrations.CreateModel(
            name='BulletinLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devoir_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='moyenne devoirs')),
                ('compo_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='note composition')),
                ('final_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='moyenne finale matière')),
                ('weighted_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='note pondérée (x coefficient)')),
                ('appreciation', models.CharField(blank=True, max_length=50, verbose_name='appréciation matière')),
                ('rank_in_subject', models.PositiveIntegerField(blank=True, null=True, verbose_name='rang dans la matière')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='schools.bulletin', verbose_name='bulletin')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_lines', to='schools.classsubject', verbose_name='matière de classe')),
            ],
            options={
                'verbose_name': 'ligne de bulletin',
                'verbose_name_plural': 'lignes de bulletin',
                'ordering': ['class_subject__order', 'class_subject__subject__name'],
            },
        ),
        migrations.CreateModel(
            name='AppreciationScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_grade', models.DecimalField(decimal_places=2, help_text='Seuil inférieur (inclus) pour cette appréciation.', max_digits=5, verbose_name='note minimale')),
                ('label', models.CharField(max_length=50, verbose_name='appréciation')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciation_scales', to='schools.school', verbose_name='école')),
            ],
            options={
                'verbose_name': "barème d'appréciation",
                'verbose_name_plural': "barèmes d'appréciation",
                'ordering': ['-min_grade'],
                'unique_together': {('school', 'label')},
            },
        ),
        migrations.AddIndex(
            model_name='bulletin',
            index=models.Index(fields=['school_class', 'period'], name='bul_class_period_idx'),
        ),
        migrations.AddIndex(
            model_name='bulletin',
            index=models.Index(fields=['student', 'period'], name='bul_student_period_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bulletin',
            unique_together={('student', 'period')},
        ),
    ]
