# Generated by Django 5.1.15 on 2026-06-11 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_alter_schoolclass_unique_together_and_more'),
        ('students', '0002_student_v2_access_code_parent_indexes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolyear',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='students.student', verbose_name='élève'),
        ),
        migrations.AlterField(
            model_name='note',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_notes', to='students.student', verbose_name='élève'),
        ),
        migrations.AddConstraint(
            model_name='schoolyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'name'), name='unique_active_schoolyear_per_school'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'name'), name='unique_active_subject_per_school'),
        ),
    ]
