# Generated by Django 5.1.15 on 2026-06-13 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_receipt_signer_remove_primary_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinconfig',
            name='ministry_line1',
            field=models.CharField(blank=True, default="MINISTERE DE L'EDUCATION NATIONALE", max_length=200, verbose_name='ministère — ligne 1'),
        ),
        migrations.AlterField(
            model_name='bulletinconfig',
            name='republic_line1',
            field=models.CharField(blank=True, default='REPUBLIQUE DU MALI', max_length=200, verbose_name='république — ligne 1'),
        ),
        migrations.AlterField(
            model_name='bulletinconfig',
            name='republic_line2',
            field=models.CharField(blank=True, default='UN PEUPLE - UN BUT - UNE FOI', max_length=200, verbose_name='république — ligne 2 (devise)'),
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['school', 'is_active'], name='schoolclass_school_active_idx'),
        ),
    ]
