# Generated by Django 5.1.15 on 2026-06-13 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_add_composite_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom du groupe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_groups', to=settings.AUTH_USER_MODEL, verbose_name='promoteur')),
            ],
            options={
                'verbose_name': 'groupe scolaire',
                'verbose_name_plural': 'groupes scolaires',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='school',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='schools.schoolgroup', verbose_name='groupe scolaire'),
        ),
    ]
