# Generated by Django 5.1.15 on 2026-06-14 06:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_add_school_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, default=Decimal('2.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))], verbose_name="durée d'un cours (heures)"),
        ),
        migrations.AddField(
            model_name='school',
            name='accounting_enabled',
            field=models.BooleanField(default=False, verbose_name='module comptabilité activé'),
        ),
    ]
