# Generated by Django 5.1.15 on 2026-06-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_add_duration_hours_accounting_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#4F46E5', max_length=7, verbose_name='couleur'),
        ),
    ]
