# Generated by Django 5.1.15 on 2026-06-17 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_update_subject_color_default'),
        ('students', '0005_add_student_auth_gamification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('body', models.TextField(verbose_name='contenu')),
                ('audience', models.CharField(choices=[('school', "Tous les parents de l'école"), ('class', "Parents d'une classe"), ('student', "Parent d'un élève spécifique")], default='school', max_length=10, verbose_name='audience')),
                ('is_published', models.BooleanField(default=False, verbose_name='publiée')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publiée le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_announcements', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='schools.school', verbose_name='école')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='schools.schoolclass', verbose_name='classe ciblée')),
                ('target_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='students.student', verbose_name='élève ciblé')),
            ],
            options={
                'verbose_name': 'annonce',
                'verbose_name_plural': 'annonces',
                'ordering': ['-created_at'],
            },
        ),
    ]
