# Generated by Django 5.1.15 on 2026-06-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_add_school_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='short_name',
            field=models.CharField(blank=True, help_text="Affiché dans la barre latérale et l'en-tête. Ex : EPF Sundiata. Laissé vide = le nom complet est utilisé.", max_length=30, verbose_name='nom court'),
        ),
    ]
