# Generated by Django 5.1.15 on 2026-06-29 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_school_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='position')),
                ('name', models.CharField(max_length=40, verbose_name='nom')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_columns', to='schools.classsubject', verbose_name='matière de classe')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_columns', to='schools.period', verbose_name='période')),
            ],
            options={
                'verbose_name': "colonne d'évaluation",
                'verbose_name_plural': "colonnes d'évaluation",
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('class_subject', 'period', 'position'), name='uniq_eval_col_cs_period_position')],
            },
        ),
    ]
