# Generated by Django 5.1.15 on 2026-06-30 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_evaluationcolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='absence_deduction',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Montant déduit du salaire d'un permanent par cours absent (0 = aucune retenue).", max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='retenue par absence (FCFA)'),
        ),
    ]
