# Generated by Django 5.1.15 on 2026-07-01 14:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_school_absence_deduction'),
        ('students', '0007_backfill_active_enrollments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormativeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('eval_type', models.CharField(choices=[('interro_ecrite', 'Interrogation écrite'), ('interro_orale', 'Interrogation orale'), ('devoir_maison', 'Devoir maison'), ('autre', 'Autre')], default='interro_ecrite', max_length=20, verbose_name='type')),
                ('title', models.CharField(blank=True, max_length=80, verbose_name='libellé')),
                ('max_grade', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='note maximale')),
                ('is_published_to_parent', models.BooleanField(default=False, verbose_name='publiée au parent')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publiée le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formative_evaluations', to='schools.classsubject', verbose_name='matière de classe')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_formative_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formative_evaluations', to='schools.period', verbose_name='période')),
            ],
            options={
                'verbose_name': 'évaluation formative',
                'verbose_name_plural': 'évaluations formatives',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormativeGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='note')),
                ('is_absent', models.BooleanField(default=False, verbose_name='absent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='schools.formativeevaluation', verbose_name='évaluation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formative_grades', to='students.student', verbose_name='élève')),
            ],
            options={
                'verbose_name': 'note formative',
                'verbose_name_plural': 'notes formatives',
                'ordering': ['student__full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='formativeevaluation',
            index=models.Index(fields=['class_subject', 'period'], name='formeval_cs_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='formativegrade',
            constraint=models.UniqueConstraint(fields=('evaluation', 'student'), name='uniq_formative_grade_eval_student'),
        ),
    ]
