# Generated by Django 5.1.15 on 2026-07-01 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_formativeevaluation_formativegrade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteEntryGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='accordée le')),
                ('expires_at', models.DateTimeField(blank=True, help_text="Laisser vide = ouverte jusqu'à révocation.", null=True, verbose_name='expire le')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_grants', to='schools.classsubject', verbose_name='matière de classe')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_note_entries', to=settings.AUTH_USER_MODEL, verbose_name='accordée par')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_grants', to='schools.period', verbose_name='période')),
            ],
            options={
                'verbose_name': 'ouverture de saisie ciblée',
                'verbose_name_plural': 'ouvertures de saisie ciblées',
                'constraints': [models.UniqueConstraint(fields=('class_subject', 'period'), name='uniq_note_entry_grant_cs_period')],
            },
        ),
    ]
