# Generated by Django 5.1.15 on 2026-07-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_noteentrygrant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsubject',
            name='coeff_compo',
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='coeff_devoirs',
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='note_system',
        ),
    ]
