# Generated by Django 5.1.15 on 2026-07-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_remove_classsubject_coeff_compo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(blank=True, max_length=7, verbose_name='couleur'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='abréviation'),
        ),
    ]
