# Generated by Django 5.1.15 on 2026-07-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_alter_subject_color_alter_subject_short_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='period',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='period',
            name='education_level',
            field=models.CharField(blank=True, choices=[('prescolaire', 'Préscolaire'), ('fondamental_1', 'Fondamental 1er Cycle'), ('fondamental_2', 'Fondamental 2ème Cycle'), ('secondaire_gen', 'Secondaire Général'), ('secondaire_pro', 'Secondaire Professionnel'), ('superieur', 'Enseignement Supérieur')], help_text="Cycle concerné. Vide = s'applique à toute l'école.", max_length=20, null=True, verbose_name='cycle'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period_type',
            field=models.CharField(choices=[('composition', 'Composition'), ('trimester', 'Trimestre'), ('semester', 'Semestre'), ('custom', 'Personnalisé')], default='trimester', max_length=12, verbose_name='type'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(condition=models.Q(('education_level__isnull', True)), fields=('school_year', 'name'), name='uniq_period_year_name_nocycle'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(condition=models.Q(('education_level__isnull', False)), fields=('school_year', 'education_level', 'name'), name='uniq_period_year_cycle_name'),
        ),
    ]
