# Generated by Django 5.1.15 on 2026-07-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_alter_period_unique_together_period_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='fin'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='début'),
        ),
    ]
