# Generated by Django 5.1.15 on 2026-07-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_alter_period_end_date_alter_period_start_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='period',
            name='uniq_period_year_name_nocycle',
        ),
        migrations.AddField(
            model_name='period',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_periods', to='schools.schoolclass', verbose_name='classe personnalisée'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(condition=models.Q(('education_level__isnull', True), ('school_class__isnull', True)), fields=('school_year', 'name'), name='uniq_period_year_name_school'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(condition=models.Q(('school_class__isnull', False)), fields=('school_year', 'school_class', 'name'), name='uniq_period_year_class_name'),
        ),
    ]
