# Generated by Django 5.1.15 on 2026-07-09 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0025_remove_period_uniq_period_year_name_nocycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='libellé')),
                ('day', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')], help_text='Vide = tous les jours.', null=True, verbose_name='jour')),
                ('start_time', models.TimeField(verbose_name='début')),
                ('end_time', models.TimeField(verbose_name='fin')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_breaks', to='schools.school', verbose_name='école')),
            ],
            options={
                'verbose_name': 'pause',
                'verbose_name_plural': 'pauses',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')], verbose_name='jour')),
                ('start_time', models.TimeField(verbose_name='début')),
                ('end_time', models.TimeField(verbose_name='fin')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='salle')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schools.classsubject', verbose_name='cours')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_slots', to='schools.schoolyear', verbose_name='année scolaire')),
            ],
            options={
                'verbose_name': 'créneau de cours',
                'verbose_name_plural': 'créneaux de cours',
                'ordering': ['day', 'start_time'],
                'indexes': [models.Index(fields=['school_year', 'day'], name='slot_year_day_idx')],
            },
        ),
    ]
