# Generated by Django 5.1.15 on 2026-07-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0026_schoolbreak_courseslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseslot',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='jour'),
        ),
        migrations.AlterField(
            model_name='schoolbreak',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Vide = tous les jours.', null=True, verbose_name='jour'),
        ),
    ]
