# Generated by Django 5.1.15 on 2026-07-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0027_alter_courseslot_day_alter_schoolbreak_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsubject',
            name='duration_hours',
        ),
    ]
