# Generated by Django 5.1.15 on 2026-06-14 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0013_add_duration_hours_accounting_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('subject', models.CharField(help_text='Ex: Mathématiques, SVT, Français', max_length=100, verbose_name='matière')),
                ('subject_type', models.CharField(choices=[('literary', 'Littéraire'), ('scientific', 'Scientifique'), ('math', 'Mathématiques'), ('language', 'Langue'), ('code', 'Informatique'), ('accounting', 'Comptabilité'), ('geography', 'Géographie/Histoire'), ('other', 'Autre')], default='other', max_length=20, verbose_name='type de matière')),
                ('level', models.CharField(choices=[('prescolaire', 'Préscolaire'), ('fondamental_1', 'Fondamental 1er Cycle'), ('fondamental_2', 'Fondamental 2ème Cycle'), ('secondaire_gen', 'Secondaire Général'), ('secondaire_pro', 'Secondaire Professionnel'), ('superieur', 'Enseignement Supérieur')], default='fondamental_1', max_length=30, verbose_name='niveau')),
                ('level_detail', models.CharField(blank=True, help_text='Ex: 6ème Année, Terminale A', max_length=50, verbose_name='détail niveau')),
                ('language', models.CharField(default='fr', max_length=5, verbose_name='langue')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='lessons/sources/%Y/%m/', verbose_name='fichier source')),
                ('source_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('text', 'Texte')], default='pdf', max_length=10, verbose_name='type source')),
                ('structured_content', models.JSONField(blank=True, help_text='Blocs de leçon générés par IA', null=True, verbose_name='contenu structuré')),
                ('quiz_data', models.JSONField(blank=True, help_text='Quiz générés par IA', null=True, verbose_name='quiz')),
                ('story_data', models.JSONField(blank=True, help_text='Session de compréhension', null=True, verbose_name='story')),
                ('flashcards_data', models.JSONField(blank=True, help_text='Flashcards pour répétition espacée', null=True, verbose_name='flashcards')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('processing', 'En cours de génération'), ('ready', 'Prête'), ('error', 'Erreur')], default='draft', max_length=20, verbose_name='statut')),
                ('processing_error', models.TextField(blank=True, verbose_name='erreur')),
                ('ai_provider_used', models.CharField(blank=True, choices=[('claude', 'Claude (Anthropic)'), ('gemini', 'Gemini (Google)')], max_length=20, verbose_name='IA utilisée')),
                ('generation_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='coût génération USD')),
                ('generation_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentatives')),
                ('is_public', models.BooleanField(default=False, help_text='Visible dans la bibliothèque', verbose_name='partagée')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='vues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schools.school', verbose_name='école')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
            ],
            options={
                'verbose_name': 'leçon',
                'verbose_name_plural': 'leçons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('deployed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_deployments', to=settings.AUTH_USER_MODEL, verbose_name='déployée par')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='lessons.lesson', verbose_name='leçon')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_deployments', to='schools.school', verbose_name='école')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_deployments', to='schools.schoolclass', verbose_name='classe')),
            ],
            options={
                'verbose_name': 'déploiement leçon',
                'verbose_name_plural': 'déploiements leçons',
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['school', 'status'], name='lesson_school_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'status'], name='lesson_teacher_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['level', 'subject_type'], name='lesson_level_type_idx'),
        ),
        migrations.AddIndex(
            model_name='lessondeployment',
            index=models.Index(fields=['school', 'is_active'], name='deploy_school_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessondeployment',
            unique_together={('lesson', 'school_class')},
        ),
    ]
