# Generated by Django 5.1.15 on 2026-06-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial_lessons_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='format_version',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = format historique ; 2 = format v2 (unité/concepts/passes)', verbose_name='version de format'),
        ),
    ]
