# Generated by Django 5.1.15 on 2026-06-24 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_format_version'),
        ('schools', '0015_add_school_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('subject', models.CharField(help_text='Ex: Mathématiques, SVT, Français', max_length=100, verbose_name='matière')),
                ('subject_type', models.CharField(choices=[('literary', 'Littéraire'), ('scientific', 'Scientifique'), ('math', 'Mathématiques'), ('language', 'Langue'), ('code', 'Informatique'), ('accounting', 'Comptabilité'), ('geography', 'Géographie/Histoire'), ('other', 'Autre')], default='other', max_length=20, verbose_name='type de matière')),
                ('level', models.CharField(choices=[('prescolaire', 'Préscolaire'), ('fondamental_1', 'Fondamental 1er Cycle'), ('fondamental_2', 'Fondamental 2ème Cycle'), ('secondaire_gen', 'Secondaire Général'), ('secondaire_pro', 'Secondaire Professionnel'), ('superieur', 'Enseignement Supérieur')], default='fondamental_1', max_length=30, verbose_name='niveau')),
                ('level_detail', models.CharField(blank=True, help_text='Ex: 6ème Année, Terminale A', max_length=50, verbose_name='détail niveau')),
                ('language', models.CharField(default='fr', max_length=5, verbose_name='langue')),
                ('direction', models.CharField(choices=[('ltr', 'Gauche → droite'), ('rtl', 'Droite → gauche (arabe)')], default='ltr', max_length=3, verbose_name='sens de lecture')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='units/sources/%Y/%m/', verbose_name='fichier source')),
                ('source_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('text', 'Texte')], default='pdf', max_length=10, verbose_name='type source')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('processing', 'En cours de génération'), ('ready', 'Prête'), ('error', 'Erreur')], default='draft', max_length=20, verbose_name='statut')),
                ('processing_error', models.TextField(blank=True, verbose_name='erreur')),
                ('ai_provider_used', models.CharField(blank=True, choices=[('claude', 'Claude (Anthropic)'), ('gemini', 'Gemini (Google)')], max_length=20, verbose_name='IA utilisée')),
                ('generation_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='coût génération USD')),
                ('generation_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentatives')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='schools.school', verbose_name='école')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
            ],
            options={
                'verbose_name': 'unité',
                'verbose_name_plural': 'unités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='lessons.unit', verbose_name='unité'),
        ),
    ]
