# Generated by Django 5.1.15 on 2026-06-24 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(verbose_name='version')),
                ('concepts_data', models.JSONField(blank=True, null=True, verbose_name='concepts')),
                ('reading_data', models.JSONField(blank=True, null=True, verbose_name='lecture')),
                ('exam_data', models.JSONField(blank=True, null=True, verbose_name='examen')),
                ('color', models.CharField(blank=True, max_length=9, verbose_name='couleur')),
                ('guide', models.CharField(blank=True, max_length=50, verbose_name='guide')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='généré le')),
                ('ai_provider_used', models.CharField(blank=True, choices=[('claude', 'Claude (Anthropic)'), ('gemini', 'Gemini (Google)')], max_length=20, verbose_name='IA utilisée')),
                ('generation_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='coût génération USD')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_versions', to='lessons.lesson', verbose_name='leçon')),
            ],
            options={
                'verbose_name': 'version de contenu',
                'verbose_name_plural': 'versions de contenu',
                'ordering': ['lesson', 'version'],
                'unique_together': {('lesson', 'version')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='active_content_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.lessoncontentversion', verbose_name='version de contenu active'),
        ),
    ]
