# Generated by Django 5.1.15 on 2026-06-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lessoncontentversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='résumé'),
        ),
    ]
