# Generated by Django 5.1.15 on 2026-06-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lesson_summary_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('processing', 'En cours de génération'), ('ready', 'Prête'), ('partial', 'Partiel'), ('error', 'Erreur')], default='draft', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('processing', 'En cours de génération'), ('ready', 'Prête'), ('partial', 'Partiel'), ('error', 'Erreur')], default='draft', max_length=20, verbose_name='statut'),
        ),
    ]
