# Generated by Django 5.1.15 on 2026-06-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lessonstatus_partial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontentversion',
            name='story_data',
            field=models.JSONField(blank=True, null=True, verbose_name='histoire'),
        ),
    ]
