# Generated by Django 5.1.15 on 2026-06-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_lessoncontentversion_story_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='generation_lock_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verrou génération'),
        ),
    ]
