# Generated by Django 5.1.15 on 2026-06-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_unit_generation_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ordre'),
        ),
    ]
