# Generated by Django 5.1.15 on 2026-06-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_lesson_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='flashcards_data',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='quiz_data',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='story_data',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='structured_content',
        ),
    ]
