# Generated by Django 5.1.15 on 2026-07-02 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_remove_lesson_flashcards_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonContentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('based_on_version', models.PositiveSmallIntegerField(blank=True, help_text="Version live au moment de l'ouverture du brouillon.", null=True, verbose_name='forké depuis la version')),
                ('concepts_data', models.JSONField(blank=True, null=True, verbose_name='concepts')),
                ('reading_data', models.JSONField(blank=True, null=True, verbose_name='lecture')),
                ('exam_data', models.JSONField(blank=True, null=True, verbose_name='examen')),
                ('story_data', models.JSONField(blank=True, null=True, verbose_name='histoire')),
                ('color', models.CharField(blank=True, max_length=9, verbose_name='couleur')),
                ('guide', models.CharField(blank=True, max_length=50, verbose_name='guide')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_draft', to='lessons.lesson', verbose_name='leçon')),
            ],
            options={
                'verbose_name': 'brouillon de contenu',
                'verbose_name_plural': 'brouillons de contenu',
            },
        ),
    ]
