# Generated by Django 5.1.15 on 2026-07-02 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_lessoncontentdraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='archivée le'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='archivée'),
        ),
        migrations.AddField(
            model_name='lessoncontentversion',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='validée le'),
        ),
        migrations.AddField(
            model_name='lessoncontentversion',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='validée par'),
        ),
    ]
