# Generated by Django 5.1.15 on 2026-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_lesson_archived_at_lesson_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontentdraft',
            name='ai_flags',
            field=models.JSONField(blank=True, null=True, verbose_name='drapeaux IA'),
        ),
    ]
