# Generated by Django 5.1.15 on 2026-06-13 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schools', '0012_add_school_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('observation', 'Observation partagée'), ('absence', 'Absence'), ('bulletin', 'Bulletin disponible'), ('payment', 'Paiement reçu'), ('info', "Message de l'école")], default='info', max_length=20, verbose_name='catégorie')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('body', models.TextField(blank=True, verbose_name='contenu')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='lien')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='lue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='schools.school', verbose_name='école')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notif_recipient_read_idx'), models.Index(fields=['school', 'category'], name='notif_school_cat_idx')],
            },
        ),
    ]
