# Generated by Django 5.1.15 on 2026-06-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_student_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('observation', 'Observation partagée'), ('absence', 'Absence'), ('bulletin', 'Bulletin disponible'), ('payment', 'Paiement reçu'), ('reminder', 'Rappel de paiement'), ('info', "Message de l'école")], default='info', max_length=20, verbose_name='catégorie'),
        ),
    ]
